# Generated by Django 5.0.6 on 2024-07-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('organisations', '0002_organisation_date_created_organisation_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text="The date the employee was enrolled on the organisation's system", null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubscriberFile',
        ),
        # migrations.CreateModel(
        #     name='SubscriberFile',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('file_type', models.CharField(choices=[('XLSX', 'XLSX'), ('XLS', 'XLS'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=50)),
        #         ('is_upload_template', models.BooleanField(blank=True, default=False, null=True)),
        #         ('file', models.FileField(upload_to='subscriber_files')),
        #         ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
        #         ('last_updated', models.DateTimeField(auto_now=True, null=True)),
        #         ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
        #     ],
        # ),
    ]
