# Generated by Django 5.0.6 on 2024-07-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_date_created_agent_last_updated_subscriberfile'),
        ('organisations', '0002_organisation_date_created_organisation_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('XLSX', 'XLSX'), ('XLS', 'XLS'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=50)),
                ('is_upload_template', models.BooleanField(blank=True, default=False, null=True)),
                ('file', models.FileField(upload_to='agent_files')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
        ),
        migrations.DeleteModel(
            name='SubscriberFile',
        ),
    ]
