# Generated by Django 5.0.6 on 2024-06-29 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_organisation_date_created_organisation_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=50)),
                ('week', models.PositiveIntegerField()),
                ('aes', models.PositiveIntegerField(help_text='Average Evaluation Score (AES)')),
                ('speed_to_answer', models.PositiveIntegerField(blank=True, help_text='Speed to answer should be in seconds', null=True)),
                ('targeted_inbound_calls', models.PositiveIntegerField(blank=True, help_text='This is Weekly Targeted inbound calls', null=True)),
                ('actual_inbound_calls', models.PositiveIntegerField(blank=True, help_text='This is Weekly inbound calls achieved by the agent', null=True)),
                ('targeted_talktime', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_talktime', models.PositiveIntegerField(blank=True, null=True)),
                ('outbound_target_calls', models.PositiveIntegerField(blank=True, help_text='This is the Weekly Outbound target calls', null=True)),
                ('actual_outbound_calls', models.PositiveIntegerField(blank=True, help_text='This is the Weekly Outbound calls achieved by the agent', null=True)),
                ('after_call_work', models.PositiveIntegerField(blank=True, help_text='This is the weekly after call work', null=True)),
                ('customer_complaint', models.PositiveIntegerField(blank=True, null=True)),
                ('csat', models.PositiveIntegerField(blank=True, help_text='This is the weekly csat', null=True)),
                ('calc_aes', models.PositiveIntegerField(help_text='This is the weekly calculated aes')),
                ('calc_speed_to_answer', models.PositiveIntegerField(blank=True, null=True)),
                ('calc_targeted_inbound_calls', models.PositiveIntegerField(help_text='This is the weekly calculated targeted inbound calls')),
                ('calc_actual_inbound_calls', models.PositiveIntegerField(help_text='This is the weekly calculated inbound calls achieved by the agent')),
                ('calc_targeted_talktime', models.PositiveBigIntegerField(blank=True, help_text='This is the weekly calculated calculated targeted talktime', null=True)),
                ('calc_outbound_target', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_calc_outbound_calls', models.PositiveIntegerField(blank=True, help_text='This is the Weekly calculated Outbound calls achieved by the agent', null=True)),
                ('calc_after_call_work', models.PositiveIntegerField(blank=True, null=True)),
                ('calc_customer_complaint', models.PositiveIntegerField(blank=True, null=True)),
                ('calc_csat', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_aes', models.PositiveIntegerField()),
                ('weighted_speed_to_answer', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_targeted_inbound_calls', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_actual_inbound_calls', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_targeted_talktime', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_actual_outbound', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_after_call_work', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_customer_complaint', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_csat', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('SP', 'SP'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_insights', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_voice_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
