# Generated by Django 5.0.6 on 2024-06-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceinsights',
            name='weighted_actual_talktime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceinsights',
            name='weighted_targeted_outbound',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
