# Generated by Django 5.0.6 on 2024-06-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0002_voiceinsights_weighted_actual_talktime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceinsights',
            name='organisation',
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='week',
            field=models.PositiveIntegerField(help_text='week should be a number'),
        ),
    ]
