# Generated by Django 5.0.6 on 2024-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0003_remove_voiceinsights_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceinsights',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceinsights',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
