# Generated by Django 5.0.6 on 2024-06-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0004_voiceinsights_date_created_and_more'),
        ('organisations', '0002_organisation_date_created_organisation_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceInsightsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('XLSX', 'XLSX'), ('XLS', 'XLS'), ('CSV', 'CSV')], max_length=50)),
                ('file', models.FileField(upload_to='voice_insights_files')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
        ),
    ]
