# Generated by Django 5.0.6 on 2024-06-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0005_voiceinsightsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceinsightsfile',
            name='is_upload_template',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsightsfile',
            name='file_type',
            field=models.CharField(choices=[('XLSX', 'XLSX'), ('XLS', 'XLS'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=50),
        ),
    ]
