# Generated by Django 5.0.6 on 2024-07-03 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0006_voiceinsightsfile_is_upload_template_and_more'),
        ('organisations', '0002_organisation_date_created_organisation_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInsightFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, choices=[('XLSX', 'XLSX'), ('XLS', 'XLS'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=150, null=True)),
                ('file_type', models.CharField(choices=[('XLSX', 'XLSX'), ('XLS', 'XLS'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=50)),
                ('is_upload_template', models.BooleanField(blank=True, default=False, null=True)),
                ('file', models.FileField(upload_to='voice_insights_files')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=50)),
                ('week', models.PositiveIntegerField(help_text='week should be a number')),
                ('aes', models.PositiveIntegerField(help_text='Average Evaluation Score (AES)')),
                ('outbound', models.PositiveIntegerField(blank=True, help_text='This is the Weekly Outbound calls achieved by the agent', null=True)),
                ('csat', models.PositiveIntegerField(blank=True, help_text='This is the weekly csat', null=True)),
                ('calc_aes', models.PositiveIntegerField(help_text='This is the weekly calculated aes')),
                ('calc_outbound', models.PositiveIntegerField(blank=True, help_text='This is the Weekly calculated Outbound calls achieved by the agent', null=True)),
                ('calc_csat', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_aes', models.PositiveIntegerField()),
                ('weighted_outbound', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_csat', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('SP', 'SP'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_up_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='VoiceInsightsFile',
        ),
    ]
