# Generated by Django 5.0.6 on 2024-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0007_campaigninsightfile_followupinsights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninsightfile',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
