# Generated by Django 5.0.6 on 2024-07-04 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0008_alter_campaigninsightfile_campaign_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherLifeFoundationInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=50)),
                ('week', models.PositiveIntegerField(help_text='week should be a number')),
                ('aes', models.PositiveIntegerField(help_text='Average Evaluation Score (AES)')),
                ('outbound', models.PositiveIntegerField(blank=True, help_text='This is the Weekly Outbound calls achieved by the agent', null=True)),
                ('csat', models.PositiveIntegerField(blank=True, help_text='This is the weekly csat', null=True)),
                ('resolved_count', models.PositiveIntegerField()),
                ('service_level', models.PositiveIntegerField()),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('SP', 'SP'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_higher_life_foundation_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
