# Generated by Django 5.0.6 on 2024-07-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0009_higherlifefoundationinsights'),
    ]

    operations = [
        migrations.AddField(
            model_name='higherlifefoundationinsights',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='higherlifefoundationinsights',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
