# Generated by Django 5.0.6 on 2024-07-04 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0012_remove_higherlifefoundationinsights_outbound_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshChatInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=50)),
                ('week', models.PositiveIntegerField(help_text='week should be a number')),
                ('aes', models.PositiveIntegerField(help_text='Average Evaluation Score (AES)')),
                ('targeted_interactions', models.PositiveIntegerField()),
                ('actual_interactions', models.PositiveIntegerField()),
                ('login_time_variance', models.PositiveIntegerField()),
                ('handling_time', models.PositiveIntegerField()),
                ('customer_complaint', models.PositiveIntegerField(help_text='Average Evaluation Score (AES)')),
                ('csat', models.PositiveIntegerField(blank=True, help_text='This is the weekly csat', null=True)),
                ('calc_aes', models.PositiveIntegerField(help_text='This is the weekly calculated aes')),
                ('calc_targeted_interactions', models.PositiveIntegerField(help_text='This is the weekly calculated targeted interactions')),
                ('calc_actual_interactions', models.PositiveIntegerField(help_text='This is the weekly calculated actual interactions')),
                ('calc_login_time_variance', models.PositiveIntegerField(help_text='This is the weekly calculated login time variance')),
                ('calc_handling_time', models.PositiveIntegerField(help_text='This is the weekly calculated handling time')),
                ('calc_customer_complaint', models.PositiveIntegerField(help_text='This is the weekly calculated customer complaint')),
                ('calc_csat', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_aes', models.PositiveIntegerField()),
                ('weighted_targeted_interactions', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_actual_interactions', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_login_time_variance', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_handling_time', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_customer_complaint', models.PositiveIntegerField(blank=True, null=True)),
                ('weighted_csat', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('SP', 'SP'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fresh_chat_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
