# Generated by Django 5.0.6 on 2024-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0014_yamuraiinsights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshchatinsights',
            name='customer_complaint',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='complaints',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='resolved_count',
            field=models.PositiveIntegerField(),
        ),
    ]
