# Generated by Django 5.0.6 on 2024-07-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0015_alter_freshchatinsights_customer_complaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freshdeskinsights',
            old_name='weighted_resolve_count',
            new_name='weighted_resolved_count',
        ),
    ]
