# Generated by Django 5.0.6 on 2024-07-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0016_rename_weighted_resolve_count_freshdeskinsights_weighted_resolved_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupinsights',
            name='agent_type',
            field=models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC'), ('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('FRESHDESK_AGENT', 'FRESHDESK Agent'), ('YAMURAI_AGENT', 'YAMURAI AGENT'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='agent_type',
            field=models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC'), ('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('FRESHDESK_AGENT', 'FRESHDESK Agent'), ('YAMURAI_AGENT', 'YAMURAI AGENT'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='agent_type',
            field=models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC'), ('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('FRESHDESK_AGENT', 'FRESHDESK Agent'), ('YAMURAI_AGENT', 'YAMURAI AGENT'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='higherlifefoundationinsights',
            name='agent_type',
            field=models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC'), ('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('FRESHDESK_AGENT', 'FRESHDESK Agent'), ('YAMURAI_AGENT', 'YAMURAI AGENT'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sasaiinsights',
            name='agent_type',
            field=models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC'), ('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('FRESHDESK_AGENT', 'FRESHDESK Agent'), ('YAMURAI_AGENT', 'YAMURAI AGENT'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='agent_type',
            field=models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC'), ('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('FRESHDESK_AGENT', 'FRESHDESK Agent'), ('YAMURAI_AGENT', 'YAMURAI AGENT'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='agent_type',
            field=models.CharField(choices=[('LVC', 'LVC'), ('HVC', 'HVC'), ('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('FRESHDESK_AGENT', 'FRESHDESK Agent'), ('YAMURAI_AGENT', 'YAMURAI AGENT'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
    ]
