# Generated by Django 5.0.6 on 2024-08-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0018_alter_followupinsights_agent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupinsights',
            name='aes',
            field=models.FloatField(help_text='Average Evaluation Score (AES)'),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='calc_aes',
            field=models.FloatField(help_text='This is the weekly calculated aes'),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='calc_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='calc_outbound',
            field=models.FloatField(blank=True, help_text='This is the Weekly calculated Outbound calls achieved by the agent', null=True),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='csat',
            field=models.FloatField(blank=True, help_text='This is the weekly csat', null=True),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='outbound',
            field=models.FloatField(blank=True, help_text='This is the Weekly Outbound calls achieved by the agent', null=True),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='weighted_aes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='weighted_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupinsights',
            name='weighted_outbound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='actual_interactions',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='aes',
            field=models.FloatField(help_text='Average Evaluation Score (AES)'),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='calc_actual_interactions',
            field=models.FloatField(help_text='This is the weekly calculated actual interactions'),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='calc_aes',
            field=models.FloatField(help_text='This is the weekly calculated aes'),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='calc_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='calc_customer_complaint',
            field=models.FloatField(help_text='This is the weekly calculated customer complaint'),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='calc_handling_time',
            field=models.FloatField(help_text='This is the weekly calculated handling time'),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='calc_login_time_variance',
            field=models.FloatField(help_text='This is the weekly calculated login time variance'),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='calc_targeted_interactions',
            field=models.FloatField(help_text='This is the weekly calculated targeted interactions'),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='csat',
            field=models.FloatField(blank=True, help_text='This is the weekly csat', null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='customer_complaint',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='handling_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='login_time_variance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='targeted_interactions',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='weighted_actual_interactions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='weighted_aes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='weighted_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='weighted_customer_complaint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='weighted_handling_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='weighted_login_time_variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='weighted_targeted_interactions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='aes',
            field=models.FloatField(help_text='Average Evaluation Score (AES)'),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='calc_aes',
            field=models.FloatField(help_text='This is the weekly calculated aes'),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='calc_complaints',
            field=models.FloatField(help_text='This is the weekly calculated complaints'),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='calc_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='calc_resolved_count',
            field=models.FloatField(help_text='This is the weekly calculated resolve count'),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='complaints',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='csat',
            field=models.FloatField(blank=True, help_text='This is the weekly csat', null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='resolved_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='weighted_aes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='weighted_complaints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='weighted_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='weighted_resolved_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='higherlifefoundationinsights',
            name='aes',
            field=models.FloatField(help_text='Average Evaluation Score (AES)'),
        ),
        migrations.AlterField(
            model_name='higherlifefoundationinsights',
            name='csat',
            field=models.FloatField(blank=True, help_text='This is the weekly csat', null=True),
        ),
        migrations.AlterField(
            model_name='higherlifefoundationinsights',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='higherlifefoundationinsights',
            name='resolved_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='higherlifefoundationinsights',
            name='service_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sasaiinsights',
            name='aes',
            field=models.FloatField(help_text='Average Evaluation Score (AES)'),
        ),
        migrations.AlterField(
            model_name='sasaiinsights',
            name='csat',
            field=models.FloatField(blank=True, help_text='This is the weekly csat', null=True),
        ),
        migrations.AlterField(
            model_name='sasaiinsights',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sasaiinsights',
            name='resolved_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sasaiinsights',
            name='service_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='actual_calc_outbound_calls',
            field=models.FloatField(blank=True, help_text='This is the Weekly calculated Outbound calls achieved by the agent', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='actual_inbound_calls',
            field=models.FloatField(blank=True, help_text='This is Weekly inbound calls achieved by the agent', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='actual_outbound_calls',
            field=models.FloatField(blank=True, help_text='This is the Weekly Outbound calls achieved by the agent', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='actual_talktime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='aes',
            field=models.FloatField(help_text='Average Evaluation Score (AES)'),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='after_call_work',
            field=models.FloatField(blank=True, help_text='This is the weekly after call work', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_actual_inbound_calls',
            field=models.FloatField(help_text='This is the weekly calculated inbound calls achieved by the agent'),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_aes',
            field=models.FloatField(help_text='This is the weekly calculated aes'),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_after_call_work',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_customer_complaint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_outbound_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_speed_to_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_targeted_inbound_calls',
            field=models.FloatField(help_text='This is the weekly calculated targeted inbound calls'),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='calc_targeted_talktime',
            field=models.FloatField(blank=True, help_text='This is the weekly calculated calculated targeted talktime', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='customer_complaint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='outbound_target_calls',
            field=models.FloatField(blank=True, help_text='This is the Weekly Outbound target calls', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='speed_to_answer',
            field=models.FloatField(blank=True, help_text='Speed to answer should be in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='targeted_inbound_calls',
            field=models.FloatField(blank=True, help_text='This is Weekly Targeted inbound calls', null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='targeted_talktime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_actual_inbound_calls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_actual_outbound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_actual_talktime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_aes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_after_call_work',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_csat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_customer_complaint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_speed_to_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_targeted_inbound_calls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_targeted_outbound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='weighted_targeted_talktime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='aes',
            field=models.FloatField(help_text='Average Evaluation Score (AES)'),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='calc_aes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='calc_csat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='calc_resolved_queries',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='csat',
            field=models.FloatField(blank=True, help_text='This is the weekly csat', null=True),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='resolved_queries',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='weighted_aes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='weighted_csat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='weighted_resolved_queries',
            field=models.FloatField(),
        ),
    ]
