# Generated by Django 5.0.6 on 2024-08-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0019_alter_followupinsights_aes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupinsights',
            name='managed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='freshchatinsights',
            name='managed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='freshdeskinsights',
            name='managed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='higherlifefoundationinsights',
            name='managed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sasaiinsights',
            name='managed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='voiceinsights',
            name='managed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='yamuraiinsights',
            name='managed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
