# Generated by Django 5.0.6 on 2024-08-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0020_followupinsights_managed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceinsights',
            name='csat',
            field=models.FloatField(blank=True, help_text='This is the weekly csat', null=True),
        ),
    ]
