# Generated by Django 5.0.6 on 2024-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_insights', '0021_alter_voiceinsights_csat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupinsights',
            name='agent_type',
            field=models.CharField(choices=[('FOLLOWUP_AGENT', 'FOLLOWUP AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='freshchatinsights',
            name='agent_type',
            field=models.CharField(choices=[('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='freshdeskinsights',
            name='agent_type',
            field=models.CharField(choices=[('FRESHDESK_AGENT', 'FRESHDESK AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='higherlifefoundationinsights',
            name='agent_type',
            field=models.CharField(choices=[('HLF_AGENT', 'HLF AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sasaiinsights',
            name='agent_type',
            field=models.CharField(choices=[('SASAI_AGENT', 'SASAI AGENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='voiceinsights',
            name='agent_type',
            field=models.CharField(choices=[('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='yamuraiinsights',
            name='agent_type',
            field=models.CharField(choices=[('YAMURAI_AGENT', 'YAMURAI AGENT')], max_length=50),
        ),
    ]
