from import_export import resources
from ..models import VoiceInsights


class VoiceInsightsResource(resources.ModelResource):
    class Meta:
        model = VoiceInsights
        import_id_fields = [
            "user",
            "agent_type",
            "year",
            "month",
            "week",
            "aes",
            "speed_to_answer",
            "targeted_inbound_calls",
            "actual_inbound_calls",
            "targeted_talktime",
            "actual_talktime",
            "outbound_target_calls",
            "actual_outbound_calls",
            "after_call_work",
            "customer_complaint",
            "csat",
            "calc_aes",
            "calc_speed_to_answer",
            "calc_targeted_inbound_calls",
            "calc_actual_inbound_calls",
            "calc_targeted_talktime",
            "calc_outbound_target",
            "actual_calc_outbound_calls",
            "calc_after_call_work",
            "calc_customer_complaint",
            "calc_csat",
            "weighted_aes",
            "weighted_speed_to_answer",
            "weighted_targeted_inbound_calls",
            "weighted_actual_inbound_calls",
            "weighted_targeted_talktime",
            "weighted_actual_talktime",
            "weighted_targeted_outbound",
            "weighted_actual_outbound",
            "weighted_after_call_work",
            "weighted_customer_complaint",
            "weighted_csat",
            "overall_score",
            "grade",
        ]
        fields = (
            "id",
            "user",
            "agent_type",
            "year",
            "month",
            "week",
            "aes",
            "speed_to_answer",
            "targeted_inbound_calls",
            "actual_inbound_calls",
            "targeted_talktime",
            "actual_talktime",
            "outbound_target_calls",
            "actual_outbound_calls",
            "after_call_work",
            "customer_complaint",
            "csat",
            "calc_aes",
            "calc_speed_to_answer",
            "calc_targeted_inbound_calls",
            "calc_actual_inbound_calls",
            "calc_targeted_talktime",
            "calc_outbound_target",
            "actual_calc_outbound_calls",
            "calc_after_call_work",
            "calc_customer_complaint",
            "calc_csat",
            "weighted_aes",
            "weighted_speed_to_answer",
            "weighted_targeted_inbound_calls",
            "weighted_actual_inbound_calls",
            "weighted_targeted_talktime",
            "weighted_actual_talktime",
            "weighted_targeted_outbound",
            "weighted_actual_outbound",
            "weighted_after_call_work",
            "weighted_customer_complaint",
            "weighted_csat",
            "overall_score",
            "grade",
        )
        skip_unchanged = True
        use_bulk = True
        report_skipped = False
