# Generated by Django 5.0.6 on 2024-06-27 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantPersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('CV', 'CV'), ('RESUME', 'RESUME'), ('IDENTIFICATION', 'IDENTIFICATION'), ('EDUCATIONAL', 'EDUCATIONAL')], max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='applicant_documents')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_attended', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification_type', models.CharField(blank=True, choices=[('PHD', 'PHD'), ('MASTERS', 'MASTERS'), ('DEGREE', 'DEGREE'), ('DIPLOMA', 'DIPLOMA'), ('NATIONAL CERTIFICATE', 'NATIONAL CERTIFICATE'), ('OTHER', 'OTHER')], max_length=200, null=True)),
                ('educational_level', models.CharField(blank=True, choices=[('TERTIARY', 'TERTIARY'), ('SECONDARY', 'SECONDARY'), ('PRIMARY', 'PRIMARY')], max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='users_educational_documents')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
