# Generated by Django 5.0.6 on 2024-06-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicantpersonaldocument_educationalqualification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantPersonalDocument',
            new_name='UserPersonalDocument',
        ),
    ]
