# Generated by Django 5.0.6 on 2024-06-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_applicantpersonaldocument_userpersonaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalqualification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpersonaldocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
