# Generated by Django 5.0.6 on 2024-07-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_educationalqualification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DEV', 'DEV'), ('SUPERUSER', 'SUPERUSER'), ('ADMIN', 'ADMIN'), ('AGENT', 'AGENT')], max_length=25, null=True),
        ),
    ]
