# Generated by Django 5.0.6 on 2024-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userbukuploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_type',
            field=models.CharField(choices=[('VOICE_HVC', 'VOICE HVC'), ('VOICE_LVC', 'VOICE LVC'), ('FOLLOWUP_AGENT', 'FOLLOWUP AGENT'), ('FRESHDESK_AGENT', 'FRESHDESK AGENT'), ('HLF_AGENT', 'HLF AGENT'), ('SASAI_AGENT', 'SASAI AGENT'), ('FRESHCHAT_LVC', 'FRESHCHAT LVC'), ('FRESHCHAT_HVC', 'FRESHCHAT HVC'), ('YAMURAI_AGENT', 'YAMURAI AGENT')], default='VOICE_HVC', max_length=50),
        ),
    ]
