from django.urls import path
from . import views

urlpatterns = [
    path(
        "",
        views.CreateHigherLifeFoundationInsightsView.as_view(),
        name="create_higherLifeFoundation_insights",
    ),
    path(
        "bulk-upload/",
        views.BulkUploadHigherLifeFoundationInsightsDataView.as_view(),
        name="bulk-upload_higher_life_foundation_insights",
    ),
    path(
        "upload-higher-life-foundation-insights-bulk-upload-template/",
        views.UploadHigherLifeFoundationInsightsBulkUploadTemplate.as_view(),
        name="bulk-upload_higher_life_foundation_insights_template",
    ),
    path(
        "get-higher-life-foundation-insights-bulk-upload-template/<int:organisation_id>/campaign/<str:campaign_name>/",
        views.GetHigherLifeFoundationInsightsBulkUploadTemplate.as_view(),
        name="get_bulk-upload_higher_life_foundation_insights_template",
    ),
    path(
        "get-all-bulk-upload-files-by-organisation-id/<int:organisation_id>/campaign/<str:campaign_name>/",
        views.GetHigherLifeFoundationInsightsUploadedFilesView.as_view(),
    ),
    path("<int:pk>/", views.HigherLifeFoundationInsightsReadDestroyView.as_view()),
    path("update/<int:pk>/", views.HigherLifeFoundationInsightsUpdateView.as_view()),
    path("get-all/", views.GetAllHigherLifeFoundationInsights.as_view()),
    path(
        "get-by-user-id/<int:user_id>/",
        views.GetHigherLifeFoundationInsightsByUserId.as_view(),
    ),
    path(
        "get-agents-by-organisation_id/<int:organisation_id>/",
        views.GetHigherLifeFoundationInsightsAgentsByOrganisationId.as_view(),
    ),
    path(
        "get-by-grade/<str:grade>/organisation_id/<int:organisation_id>/",
        views.GetHigherLifeFoundationInsightsByGradeAndOrganisationId.as_view(),
    ),
    path(
        "get-by-date/year/<int:year>/month/<str:month>/week/<int:week>/organisation_id/<int:organisation_id>/",
        views.GetHigherLifeFoundationInsightsByDateAndOrganisationId.as_view(),
    ),
    path(
        "get-all-average-statists-by-organisation-id/<int:organisation_id>/agent-type/<str:agent_type>/",
        views.GetAllAverageHigherLifeFoundationInsightsStatisticsView.as_view(),
    ),
    path(
        "get-all-statistics-by-organisation-id/<int:organisation_id>/year/<int:year>/month/<str:month>/week/<int:week>/agent_type/<str:agent_type>/",
        views.GetAllHigherLifeFoundationInsightsStatisticsView.as_view(),
    ),
    path(
        "get-all-statistics-by-organisation-id/<int:organisation_id>/year/<int:year>/month/<str:month>/agent_type/<str:agent_type>/",
        views.GetAllHigherLifeFoundationInsightsStatisticsWithoutWeekView.as_view(),
    ),
    path(
        "get-all-statistics-by-organisation-id/<int:organisation_id>/year/<int:year>/agent_type/<str:agent_type>/",
        views.GetAllHigherLifeFoundationInsightsStatisticsWithoutMonthAndWeekView.as_view(),
    ),
    ##########################
    path(
        "new-get-all-statistics-by-organisation-id/<int:organisation_id>/year/<int:year>/month/<str:month>/agent_type/<str:agent_type>/",
        views.NewGetAllHlfInsightsStatisticsWithWeekView.as_view(),
    ),
    path(
        "new-get-all-statistics-by-organisation-id/<int:organisation_id>/year/<int:year>/agent_type/<str:agent_type>/",
        views.NewGetAllHlfInsightsStatisticsWithMonthView.as_view(),
    ),
    path(
        "get-user-monthly-statistics-by-user-id/<int:user_id>/year/<int:year>/month/<str:month>/",
        views.GetUserMonthlyInsightsStatisticsView.as_view(),
    ),
    path(
        "get-user-yearly-statistics-by-user-id/<int:user_id>/year/<int:year>/",
        views.GetUserYearlyInsightsStatisticsView.as_view(),
    ),
    path(
        "get-total-monthly-statistics-by-organisation-id/<int:organisation_id>/user-id/<int:user_id>/year/<int:year>/agent-type/<str:agent_type>/",
        views.GetAllInsightsMonthlyStatisticsPerUserView.as_view(),
    ),
    path(
        "get-user-average-stats-by-range/<int:user_id>/year/<int:year>/start-month/<str:start_month>/end-month/<str:end_month>/",
        views.GetUserHlfInsightsStatisticsByRangeView.as_view(),
    ),
    path(
        "get-user-total-stats-by-range/<int:user_id>/year/<int:year>/start-month/<str:start_month>/end-month/<str:end_month>/",
        views.GetUserHlfInsightsTotalStatisticsByRangeView.as_view(),
    ),
]
