# Generated by Django 5.0.6 on 2024-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text="The date the employee was enrolled on the organisation's system", null=True),
        ),
        migrations.AddField(
            model_name='superuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
