# Generated by Django 5.0.6 on 2024-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
