# Generated by Django 5.0.6 on 2024-07-16 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_goals', models.TextField(blank=True, null=True)),
                ('career_journey', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('opportunities', models.TextField(blank=True, null=True)),
                ('development_goals', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('secondment', models.TextField(blank=True, null=True)),
                ('work_life_balance', models.TextField(blank=True, null=True)),
                ('personal_goals', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('career_expectations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the pdp was created', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_pdp', to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_pdp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PdpReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the pdp review was made', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdp', to='personal_development_plans.pdp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pdp_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
