# Generated by Django 5.0.6 on 2024-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_development_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdp',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
