# Generated by Django 5.0.6 on 2024-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_development_plans', '0003_alter_pdp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdp',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], default='PENDING', max_length=150, null=True),
        ),
    ]
