# Generated by Django 5.0.6 on 2024-09-18 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_score', models.FloatField(blank=True, null=True)),
                ('manager_score', models.FloatField(blank=True, null=True)),
                ('document_proof', models.FileField(blank=True, null=True, upload_to='scorecard_docs')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], default='PENDING', max_length=150, null=True)),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the scorecard was created', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective', models.TextField(blank=True, null=True)),
                ('performance_measure', models.TextField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('actual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='scorecard.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective', models.TextField(blank=True, null=True)),
                ('performance_measure', models.TextField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('actual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovations', to='scorecard.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective', models.TextField(blank=True, null=True)),
                ('performance_measure', models.TextField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('actual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='scorecard.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective', models.TextField(blank=True, null=True)),
                ('performance_measure', models.TextField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('actual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='scorecard.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the scorecard review was made', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_approver', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_recipient', to=settings.AUTH_USER_MODEL)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_clone', to='scorecard.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, help_text='The date the scorecard review was made', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_reviewer', to=settings.AUTH_USER_MODEL)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_review', to='scorecard.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective', models.TextField(blank=True, null=True)),
                ('performance_measure', models.TextField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('actual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='scorecard.scorecard')),
            ],
        ),
    ]
