# Generated by Django 5.0.6 on 2024-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text='The date the scorecard was created', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='function',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text='The date the scorecard was created', null=True),
        ),
        migrations.AddField(
            model_name='function',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text='The date the scorecard was created', null=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text='The date the scorecard was created', null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='date_created',
            field=models.DateField(auto_now_add=True, help_text='The date the scorecard was created', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
