# Generated by Django 5.0.6 on 2024-09-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_customer_date_created_customer_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
    ]
