# Generated by Django 5.0.6 on 2024-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_rename_operations_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorecardreview',
            old_name='manager_comment',
            new_name='initial_manager_comment',
        ),
        migrations.AddField(
            model_name='scorecardreview',
            name='last_manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REVIEWED', 'REVIEWED')], default='PENDING', max_length=150, null=True),
        ),
    ]
