# Generated by Django 5.0.6 on 2024-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_customer_fy_target_function_fy_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
